name: Destroy Infra
on:
  # only on dispatch
  workflow_dispatch:

permissions: write-all

env:
  AWS_REGION: "us-west-1"
  AWS_ROLE: "arn:aws:iam::270074865685:role/terraform-module-ci-test"

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - run: sudo rm -rf /nix/store
      - run: sudo install -d /nix/store
      - run: sudo chown -R "$(whoami)" /nix/store
      - run: sudo chmod 0755 /nix/store
      - uses: actions/cache/restore@v3
        id: cache-nix-restore
        with:
          path: /nix/store
          key: nix-${{ hashFiles('**/flake.nix') }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: nicknovitski/nix-develop@v1.1.0
        with:
          arguments: |
            --ignore-environment \
            --extra-experimental-features nix-command \
            --extra-experimental-features flakes \
            --keep HOME \
            --keep SSH_AUTH_SOCK \
            --keep GITHUB_TOKEN \
            --keep AWS_ROLE \
            --keep AWS_REGION \
            --keep AWS_DEFAULT_REGION \
            --keep AWS_ACCESS_KEY_ID \
            --keep AWS_SECRET_ACCESS_KEY \
            --keep AWS_SESSION_TOKEN \
            --keep TERM \
            ${{ github.workspace }}
      - uses: actions/cache/save@v3
        id: cache-nix-save
        with:
          path: /nix/store
          key: ${{ steps.cache-nix-restore.outputs.cache-primary-key }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.AWS_ROLE}}
          role-session-name: ${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
          aws-region: ${{env.AWS_REGION}}
      - uses: actions/cache/restore@v3
        id: cache-terraform-restore
        with:
          path: ${{ github.workspace }}/.terraform
          key: terraform-${{hashFiles('**/versions.tf','**/main.tf')}}
      - run: terraform init -upgrade
      - uses: actions/cache/save@v3
        id: cache-terraform-save
        with:
          path: ${{ github.workspace }}/.terraform
          key: ${{ steps.cache-terraform-restore.outputs.cache-primary-key }}
      - uses: haythem/public-ip@v1.3
        id: ip
      - name: 'Apply changes'
        shell: bash
        run: |
          eval "$(ssh-agent -s)"
          echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o ssh_key ssh.age
          chmod 0600 ssh_key
          ssh-add ssh_key
          echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o terraform.tfstate terraform.tfstate.age
          export TF_VAR_ip="${{ steps.ip.outputs.ipv4 }}"
          terraform init
          terraform destroy --auto-approve || true
          rm -rf ssh_key
          rm -rf terraform.tfstate.age
          age -e -r '${{ secrets.AGE_PUBLIC_KEY }}' -o terraform.tfstate.age terraform.tfstate
          rm -f terraform.tfstate
          git config --global user.name 'automation'
          git config --global user.email 'automation@users.noreply.github.com'
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}"
          git add -A
          git commit -s -m "New State ${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
          git push origin main
